// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	Symbol    string             `json:"symbol"`
	Name      string             `json:"name"`
	Sector    string             `json:"sector"`
	SubSector pgtype.Text        `json:"sub_sector"`
	MarketCap pgtype.Int8        `json:"market_cap"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type IntelligenceSnapshot struct {
	ID                 int64              `json:"id"`
	Symbol             string             `json:"symbol"`
	OpportunityScore   pgtype.Numeric     `json:"opportunity_score"`
	RiskScore          pgtype.Numeric     `json:"risk_score"`
	Direction          string             `json:"direction"`
	Confidence         string             `json:"confidence"`
	RiskLevel          string             `json:"risk_level"`
	IsAnomaly          bool               `json:"is_anomaly"`
	AnomalyScore       pgtype.Numeric     `json:"anomaly_score"`
	DivergenceDetected bool               `json:"divergence_detected"`
	PositiveFactors    []byte             `json:"positive_factors"`
	NegativeFactors    []byte             `json:"negative_factors"`
	SupportingFactors  []byte             `json:"supporting_factors"`
	Evidence           []byte             `json:"evidence"`
	AiResearchSummary  pgtype.Text        `json:"ai_research_summary"`
	ModelVersion       string             `json:"model_version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type SectorsDataSnapshot struct {
	ID                int64              `json:"id"`
	Symbol            string             `json:"symbol"`
	SnapshotDate      pgtype.Date        `json:"snapshot_date"`
	ValuationMetrics  []byte             `json:"valuation_metrics"`
	Financials        []byte             `json:"financials"`
	InstitutionalFlow []byte             `json:"institutional_flow"`
	RawPayload        []byte             `json:"raw_payload"`
	FetchedAt         pgtype.Timestamptz `json:"fetched_at"`
}
