// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetCompany(ctx context.Context, symbol string) (Company, error)
	GetLatestIntelligence(ctx context.Context, symbol string) (IntelligenceSnapshot, error)
	GetLatestSectorsSnapshot(ctx context.Context, symbol string) (SectorsDataSnapshot, error)
	GetRecentAnomalies(ctx context.Context, limit int32) ([]IntelligenceSnapshot, error)
	GetSectorsSnapshotByDate(ctx context.Context, arg GetSectorsSnapshotByDateParams) (SectorsDataSnapshot, error)
	GetTopOpportunities(ctx context.Context, limit int32) ([]IntelligenceSnapshot, error)
	GetTopRisks(ctx context.Context, limit int32) ([]IntelligenceSnapshot, error)
	InsertIntelligenceSnapshot(ctx context.Context, arg InsertIntelligenceSnapshotParams) (IntelligenceSnapshot, error)
	ListCompanies(ctx context.Context) ([]Company, error)
	ListCompaniesBySector(ctx context.Context, sector string) ([]Company, error)
	UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (Company, error)
	UpsertSectorsSnapshot(ctx context.Context, arg UpsertSectorsSnapshotParams) (SectorsDataSnapshot, error)
}

var _ Querier = (*Queries)(nil)
