// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompany = `-- name: GetCompany :one
SELECT symbol, name, sector, sub_sector, market_cap, created_at, updated_at
FROM companies
WHERE symbol = $1
LIMIT 1
`

func (q *Queries) GetCompany(ctx context.Context, symbol string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, symbol)
	var i Company
	err := row.Scan(
		&i.Symbol,
		&i.Name,
		&i.Sector,
		&i.SubSector,
		&i.MarketCap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT symbol, name, sector, sub_sector, market_cap, created_at, updated_at
FROM companies
ORDER BY symbol ASC
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.Symbol,
			&i.Name,
			&i.Sector,
			&i.SubSector,
			&i.MarketCap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesBySector = `-- name: ListCompaniesBySector :many
SELECT symbol, name, sector, sub_sector, market_cap, created_at, updated_at
FROM companies
WHERE sector = $1
ORDER BY symbol ASC
`

func (q *Queries) ListCompaniesBySector(ctx context.Context, sector string) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompaniesBySector, sector)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.Symbol,
			&i.Name,
			&i.Sector,
			&i.SubSector,
			&i.MarketCap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO companies (
    symbol, name, sector, sub_sector, market_cap, updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
ON CONFLICT (symbol) DO UPDATE SET
    name = EXCLUDED.name,
    sector = EXCLUDED.sector,
    sub_sector = EXCLUDED.sub_sector,
    market_cap = EXCLUDED.market_cap,
    updated_at = NOW()
RETURNING symbol, name, sector, sub_sector, market_cap, created_at, updated_at
`

type UpsertCompanyParams struct {
	Symbol    string      `json:"symbol"`
	Name      string      `json:"name"`
	Sector    string      `json:"sector"`
	SubSector pgtype.Text `json:"sub_sector"`
	MarketCap pgtype.Int8 `json:"market_cap"`
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, upsertCompany,
		arg.Symbol,
		arg.Name,
		arg.Sector,
		arg.SubSector,
		arg.MarketCap,
	)
	var i Company
	err := row.Scan(
		&i.Symbol,
		&i.Name,
		&i.Sector,
		&i.SubSector,
		&i.MarketCap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
