// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intelligence.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestIntelligence = `-- name: GetLatestIntelligence :one
SELECT id, symbol, opportunity_score, risk_score, direction, confidence, risk_level, is_anomaly, anomaly_score, divergence_detected, positive_factors, negative_factors, supporting_factors, evidence, ai_research_summary, model_version, created_at FROM intelligence_snapshots
WHERE symbol = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestIntelligence(ctx context.Context, symbol string) (IntelligenceSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestIntelligence, symbol)
	var i IntelligenceSnapshot
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.OpportunityScore,
		&i.RiskScore,
		&i.Direction,
		&i.Confidence,
		&i.RiskLevel,
		&i.IsAnomaly,
		&i.AnomalyScore,
		&i.DivergenceDetected,
		&i.PositiveFactors,
		&i.NegativeFactors,
		&i.SupportingFactors,
		&i.Evidence,
		&i.AiResearchSummary,
		&i.ModelVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentAnomalies = `-- name: GetRecentAnomalies :many
SELECT id, symbol, opportunity_score, risk_score, direction, confidence, risk_level, is_anomaly, anomaly_score, divergence_detected, positive_factors, negative_factors, supporting_factors, evidence, ai_research_summary, model_version, created_at FROM intelligence_snapshots
WHERE is_anomaly = true OR divergence_detected = true
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetRecentAnomalies(ctx context.Context, limit int32) ([]IntelligenceSnapshot, error) {
	rows, err := q.db.Query(ctx, getRecentAnomalies, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntelligenceSnapshot{}
	for rows.Next() {
		var i IntelligenceSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.OpportunityScore,
			&i.RiskScore,
			&i.Direction,
			&i.Confidence,
			&i.RiskLevel,
			&i.IsAnomaly,
			&i.AnomalyScore,
			&i.DivergenceDetected,
			&i.PositiveFactors,
			&i.NegativeFactors,
			&i.SupportingFactors,
			&i.Evidence,
			&i.AiResearchSummary,
			&i.ModelVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopOpportunities = `-- name: GetTopOpportunities :many
SELECT id, symbol, opportunity_score, risk_score, direction, confidence, risk_level, is_anomaly, anomaly_score, divergence_detected, positive_factors, negative_factors, supporting_factors, evidence, ai_research_summary, model_version, created_at FROM intelligence_snapshots
ORDER BY opportunity_score DESC, created_at DESC
LIMIT $1
`

func (q *Queries) GetTopOpportunities(ctx context.Context, limit int32) ([]IntelligenceSnapshot, error) {
	rows, err := q.db.Query(ctx, getTopOpportunities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntelligenceSnapshot{}
	for rows.Next() {
		var i IntelligenceSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.OpportunityScore,
			&i.RiskScore,
			&i.Direction,
			&i.Confidence,
			&i.RiskLevel,
			&i.IsAnomaly,
			&i.AnomalyScore,
			&i.DivergenceDetected,
			&i.PositiveFactors,
			&i.NegativeFactors,
			&i.SupportingFactors,
			&i.Evidence,
			&i.AiResearchSummary,
			&i.ModelVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRisks = `-- name: GetTopRisks :many
SELECT id, symbol, opportunity_score, risk_score, direction, confidence, risk_level, is_anomaly, anomaly_score, divergence_detected, positive_factors, negative_factors, supporting_factors, evidence, ai_research_summary, model_version, created_at FROM intelligence_snapshots
ORDER BY risk_score DESC, created_at DESC
LIMIT $1
`

func (q *Queries) GetTopRisks(ctx context.Context, limit int32) ([]IntelligenceSnapshot, error) {
	rows, err := q.db.Query(ctx, getTopRisks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntelligenceSnapshot{}
	for rows.Next() {
		var i IntelligenceSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.OpportunityScore,
			&i.RiskScore,
			&i.Direction,
			&i.Confidence,
			&i.RiskLevel,
			&i.IsAnomaly,
			&i.AnomalyScore,
			&i.DivergenceDetected,
			&i.PositiveFactors,
			&i.NegativeFactors,
			&i.SupportingFactors,
			&i.Evidence,
			&i.AiResearchSummary,
			&i.ModelVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIntelligenceSnapshot = `-- name: InsertIntelligenceSnapshot :one
INSERT INTO intelligence_snapshots (
    symbol, opportunity_score, risk_score, direction, confidence, risk_level,
    is_anomaly, anomaly_score, divergence_detected, positive_factors, negative_factors,
    supporting_factors, evidence, ai_research_summary, model_version, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW()
)
RETURNING id, symbol, opportunity_score, risk_score, direction, confidence, risk_level, is_anomaly, anomaly_score, divergence_detected, positive_factors, negative_factors, supporting_factors, evidence, ai_research_summary, model_version, created_at
`

type InsertIntelligenceSnapshotParams struct {
	Symbol             string         `json:"symbol"`
	OpportunityScore   pgtype.Numeric `json:"opportunity_score"`
	RiskScore          pgtype.Numeric `json:"risk_score"`
	Direction          string         `json:"direction"`
	Confidence         string         `json:"confidence"`
	RiskLevel          string         `json:"risk_level"`
	IsAnomaly          bool           `json:"is_anomaly"`
	AnomalyScore       pgtype.Numeric `json:"anomaly_score"`
	DivergenceDetected bool           `json:"divergence_detected"`
	PositiveFactors    []byte         `json:"positive_factors"`
	NegativeFactors    []byte         `json:"negative_factors"`
	SupportingFactors  []byte         `json:"supporting_factors"`
	Evidence           []byte         `json:"evidence"`
	AiResearchSummary  pgtype.Text    `json:"ai_research_summary"`
	ModelVersion       string         `json:"model_version"`
}

func (q *Queries) InsertIntelligenceSnapshot(ctx context.Context, arg InsertIntelligenceSnapshotParams) (IntelligenceSnapshot, error) {
	row := q.db.QueryRow(ctx, insertIntelligenceSnapshot,
		arg.Symbol,
		arg.OpportunityScore,
		arg.RiskScore,
		arg.Direction,
		arg.Confidence,
		arg.RiskLevel,
		arg.IsAnomaly,
		arg.AnomalyScore,
		arg.DivergenceDetected,
		arg.PositiveFactors,
		arg.NegativeFactors,
		arg.SupportingFactors,
		arg.Evidence,
		arg.AiResearchSummary,
		arg.ModelVersion,
	)
	var i IntelligenceSnapshot
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.OpportunityScore,
		&i.RiskScore,
		&i.Direction,
		&i.Confidence,
		&i.RiskLevel,
		&i.IsAnomaly,
		&i.AnomalyScore,
		&i.DivergenceDetected,
		&i.PositiveFactors,
		&i.NegativeFactors,
		&i.SupportingFactors,
		&i.Evidence,
		&i.AiResearchSummary,
		&i.ModelVersion,
		&i.CreatedAt,
	)
	return i, err
}
