// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sectors_snapshots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSectorsSnapshot = `-- name: GetLatestSectorsSnapshot :one
SELECT id, symbol, snapshot_date, valuation_metrics, financials, institutional_flow, raw_payload, fetched_at
FROM sectors_data_snapshots
WHERE symbol = $1
ORDER BY snapshot_date DESC, fetched_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSectorsSnapshot(ctx context.Context, symbol string) (SectorsDataSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSectorsSnapshot, symbol)
	var i SectorsDataSnapshot
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.SnapshotDate,
		&i.ValuationMetrics,
		&i.Financials,
		&i.InstitutionalFlow,
		&i.RawPayload,
		&i.FetchedAt,
	)
	return i, err
}

const getSectorsSnapshotByDate = `-- name: GetSectorsSnapshotByDate :one
SELECT id, symbol, snapshot_date, valuation_metrics, financials, institutional_flow, raw_payload, fetched_at
FROM sectors_data_snapshots
WHERE symbol = $1 AND snapshot_date = $2
LIMIT 1
`

type GetSectorsSnapshotByDateParams struct {
	Symbol       string      `json:"symbol"`
	SnapshotDate pgtype.Date `json:"snapshot_date"`
}

func (q *Queries) GetSectorsSnapshotByDate(ctx context.Context, arg GetSectorsSnapshotByDateParams) (SectorsDataSnapshot, error) {
	row := q.db.QueryRow(ctx, getSectorsSnapshotByDate, arg.Symbol, arg.SnapshotDate)
	var i SectorsDataSnapshot
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.SnapshotDate,
		&i.ValuationMetrics,
		&i.Financials,
		&i.InstitutionalFlow,
		&i.RawPayload,
		&i.FetchedAt,
	)
	return i, err
}

const upsertSectorsSnapshot = `-- name: UpsertSectorsSnapshot :one
INSERT INTO sectors_data_snapshots (
    symbol, snapshot_date, valuation_metrics, financials, institutional_flow, raw_payload, fetched_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
ON CONFLICT (symbol, snapshot_date) DO UPDATE SET
    valuation_metrics = EXCLUDED.valuation_metrics,
    financials = EXCLUDED.financials,
    institutional_flow = EXCLUDED.institutional_flow,
    raw_payload = EXCLUDED.raw_payload,
    fetched_at = NOW()
RETURNING id, symbol, snapshot_date, valuation_metrics, financials, institutional_flow, raw_payload, fetched_at
`

type UpsertSectorsSnapshotParams struct {
	Symbol            string      `json:"symbol"`
	SnapshotDate      pgtype.Date `json:"snapshot_date"`
	ValuationMetrics  []byte      `json:"valuation_metrics"`
	Financials        []byte      `json:"financials"`
	InstitutionalFlow []byte      `json:"institutional_flow"`
	RawPayload        []byte      `json:"raw_payload"`
}

func (q *Queries) UpsertSectorsSnapshot(ctx context.Context, arg UpsertSectorsSnapshotParams) (SectorsDataSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertSectorsSnapshot,
		arg.Symbol,
		arg.SnapshotDate,
		arg.ValuationMetrics,
		arg.Financials,
		arg.InstitutionalFlow,
		arg.RawPayload,
	)
	var i SectorsDataSnapshot
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.SnapshotDate,
		&i.ValuationMetrics,
		&i.Financials,
		&i.InstitutionalFlow,
		&i.RawPayload,
		&i.FetchedAt,
	)
	return i, err
}
